config_setter_name: diver_finetune
model_spec:
  constructor_name: diver_finetune
  params:
    d_model: 256
    deepspeed_pth_format: true
    e_layer: 12
    foundation_dir: models/diver/pretrained_model/256_mp_rank_00_model_states.pt
    freeze_foundation: true
    ft_config: flatten_linear
    ft_mup: false
    mup_weights: true
    output_dim: 1
    patch_sampling_rate: 500
    patch_size: 50
  sub_models: {}
task_config:
  data_params:
    data_root: data
    do_drop_bads: true
    electrode_file_path: null
    signal_unit: uV
    target_sr: 500
    use_high_gamma: false
    window_width: 1.0
    subject_ids:
    - 4
    channel_reg_ex: null
    per_subject_electrodes: null
  task_name: iu_boundary_task
  task_specific_config:
    iu_boundaries_csv_path: processed_data/iu_boundaries.csv
    negative_margin_s: 0.5
    negatives_per_positive: 2
training_params:
  batch_size: 4
  early_stopping_metric: f1_logits
  early_stopping_patience: 10
  epochs: 100
  lag_step_size: 500
  learning_rate: 1.0e-05
  loss_weights:
  - 1.0
  losses:
  - bce_with_logits
  max_lag: 1500
  metrics:
  - roc_auc
  - sensitivity_logits
  - specificity_logits
  - f1_logits
  - precision_logits
  - acc_logits
  min_lag: -1000
  n_folds: 5
  smaller_is_better: false
  weight_decay: 1.0e-05
  fold_ids:
  - 1
  - 5
trial_name: diver_subject4_full_iu_boundary
