site_name: Podcast Benchmark
site_description: A benchmarking framework for neural decoding from podcast listening data
site_author: Hasson Lab
repo_url: https://github.com/hassonlab/podcast-benchmark
repo_name: hassonlab/podcast-benchmark

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Guides:
      - Onboarding a Model: onboarding-model.md
      - Adding a Task: adding-task.md
      - Configuration: configuration.md
  - Reference:
      - Registry API: api-reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

docs_dir: docs
site_dir: site

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hassonlab/podcast-benchmark
