config_setter_name: diver_finetune
task_config:
  task_name: llm_decoding_task
  data_params:
    data_root: data
    electrode_file_path: processed_data/all_subject_sig.csv
    use_high_gamma: false
    target_sr: 500
    signal_unit: uV
    do_drop_bads: true
    window_width: 1.0
  task_specific_config:
    max_context: 32
    max_target_tokens: 16
    transcript_path: data/stimuli/podcast_transcript.csv
    prepend_space: true
    model_name: gpt2
    cache_dir: ./model_cache
training_params:
  batch_size: 4
  epochs: 100
  learning_rate: 1.0e-05
  weight_decay: 1.0e-05
  early_stopping_patience: 5
  n_folds: 5
  min_lag: -1000
  max_lag: 1500
  lag_step_size: 500
  losses:
  - cross_entropy
  loss_weights:
  - 1.0
  metrics:
  - acc_llm
  - top_1_acc_llm
  - top_5_acc_llm
  - top_10_acc_llm
  early_stopping_metric: cross_entropy
  smaller_is_better: true
  fold_ids:
  - 1
  - 5
trial_name: diver_persubject_concat_llm_decoding
model_spec:
  constructor_name: gpt2_brain
  params:
    freeze_lm: true
  sub_models:
    encoder_model:
      constructor_name: diver_finetune
      params:
        foundation_dir: models/diver/pretrained_model/256_mp_rank_00_model_states.pt
        patch_sampling_rate: 500
        patch_size: 50
        d_model: 256
        e_layer: 12
        ft_config: flatten_linear
        deepspeed_pth_format: true
        output_dim: 768
        freeze_foundation: false
        mup_weights: true
        ft_mup: false
  per_subject_feature_concat: true
