config_setter_name: foundation_feature_cache
model_spec:
  constructor_name: mlp_probe_decoder
  params:
    layer_sizes:
    - 3
    dropout: 0.0
    use_layer_norm: true
    output_dim: 3
    embedding_dim: 3
  sub_models: {}
task_config:
  data_params:
    data_root: data
    electrode_file_path: null
    target_sr: 2048
    use_high_gamma: false
    use_lip_coords: true
    window_width: 1.0
    subject_ids:
    - 2
    channel_reg_ex: null
    per_subject_electrodes: null
    preprocessing_fn_name:
    - disk_cache_preprocessor
    preprocessor_params:
    - base_preprocessing_fn_name:
      - stft_preprocessing
      - foundation_feature_cache
      base_preprocessor_params:
      - freq_channel_cutoff: 40
        nperseg: 400
        noverlap: 350
        normalizing: zscore
      - mode: normal
        batch_size: 4
        foundation_config_setter_name: popt_finetune
        foundation_model_spec:
          constructor_name: popt_finetune
          params:
            brainbert_model_dir: /scratch/gpfs/HASSON/lucy/PODCAST/podcast-benchmark/models/brainbert/pretrained_model
            max_coord_value: 5000
            model_dir: /scratch/gpfs/HASSON/lucy/PODCAST/podcast-benchmark/models/popt/pretrained_model
            use_brainbert: true
            use_lip_coords: true
            feature_cache: true
          feature_cache: true
          per_subject_feature_concat: false
          sub_models: {}
  task_name: gpt_surprise_multiclass_task
  task_specific_config:
    content_noncontent_path: processed_data/df_word_onset_with_pos_class.csv
training_params:
  batch_size: 4
  early_stopping_metric: roc_auc_multiclass
  early_stopping_patience: 10
  epochs: 100
  lag_step_size: 500
  learning_rate: 1.0e-05
  loss_weights:
  - 1.0
  losses:
  - cross_entropy
  max_lag: 1500
  metrics:
  - roc_auc_multiclass
  - f1
  - acc
  min_lag: -1000
  n_folds: 5
  smaller_is_better: false
  weight_decay: 1.0e-05
trial_name: popt_subject2_full_gpt_surprise_multiclass
