model_constructor_name: torch_ridge_model
config_setter_name: volume_level_config_setter
task_name: volume_level_encoding_task
trial_name: volume_level_torch_ridge
output_dir: results
model_dir: models
tensorboard_dir: event_logs

data_params:
  data_root: /scratch/gpfs/HASSON/gidon/pb/podcast-benchmark/data
  subject_ids: [1,2,3,4,5,6,7,8,9]
  channel_reg_ex: null
  window_width: 0.2
  preprocessing_fn_name: window_rms
  task_params:
    audio_path: /scratch/gpfs/HASSON/gidon/pb/podcast-benchmark/data/stimuli/podcast.wav
    target_sr: 512
    cutoff_hz: 8.0
    butter_order: 4
    zero_phase: true
    allow_resample_audio: true
    window_size: 200.0
    hop_size: 25.0

training_params:
  min_lag: -1000
  max_lag: 1001
  lag_step_size: 50
  lag: null
  batch_size: 128
  epochs: 100
  n_folds: 5
  losses: [mse]
  metrics: [r2]
  early_stopping_metric: r2
  weight_decay: 0.001
  learning_rate: 0.001

model_params:
  device: cuda
  embedding_dim: 1
  bias: true
  preprocessor_params: {}
  # input_channels will be auto-filled by the volume_level_config_setter from the loaded raws
