model_constructor_name: volume_level_ridge
task_name: volume_level_encoding_task
trial_name: volume_level_ridge_two_subjects
output_dir: results
data_params:
  data_root: data
  subject_ids: [1, 2]
  channel_reg_ex: null
  window_width: -1
  task_params:
    audio_path: stimuli/podcast.wav
    target_sr: 512
    cutoff_hz: 8.0
    butter_order: 4
    zero_phase: true
    allow_resample_audio: true
    window_size: 200.0
    hop_size: 25.0
training_params:
  min_lag: -1000
  max_lag: 1010
  lag_step_size: 10
  lag: null
  batch_size: 1
  epochs: 1
  n_folds: 1
model_params:
  alphas: null
  cv_splits: 10
  device: null
  verbose: true
  output_csv: ridge_summary.csv
  plot: false
  save_plot_path: ridge_plot.png
  analysis_modes:
    - pooled_electrodes
    - per_subject
    - average
  neural_log_compress: true
  neural_log_eps_scale: 0.000001
  allow_neural_resample: false
  drop_last_neural_channel: false
notes: |
  Minimal test run restricted to participants 1 and 2.
  Uses the same preprocessing and ridge settings as the full configuration.
