task_config:
  task_name: llm_decoding_task
  data_params:
    data_root: data
training_params:
  batch_size: 16
  epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
  early_stopping_patience: 15
  n_folds: 5
  min_lag: 0
  max_lag: 400
  lag_step_size: 100
  losses:
  - cross_entropy
  metrics:
  - perplexity
  early_stopping_metric: cross_entropy
  smaller_is_better: true
trial_name: llm_decoding
model_spec:
  constructor_name: gpt2_brain
  params:
    freeze_lm: true
    no_brain_encoder: true
    encoder_forward_kwargs:
      preserve_ensemble: true
