config_setter_name: popt_per_subject
model_spec:
  constructor_name: population_transformer_mlp
  params:
    model_dir: models/popt/pretrained_model
    layer_sizes:
    - 50
    dropout: 0.0
task_config:
  data_params:
    data_root: data
    electrode_file_path: processed_data/all_subject_sig.csv
    target_sr: 2048
    use_high_gamma: false
    use_lip_coords: true
    window_width: 1.0
    word_column: word
    per_subject_preprocessing: true
    preprocessing_fn_name:
    - popt_per_subject_feature_extraction
  task_name: whisper_embedding_decoding_task
  task_specific_config:
    embedding_pca_dim: 50
training_params:
  batch_size: 32
  early_stopping_metric: cosine_sim
  early_stopping_patience: 10
  epochs: 100
  fold_ids:
  - 1
  - 5
  lag_step_size: 500
  learning_rate: 0.001
  loss_weights:
  - 1.0
  losses:
  - mse
  max_lag: 1500
  metrics:
  - mse
  - corr
  - cosine_sim
  - cosine_dist
  - nll_embedding
  - pairwise_accuracy
  - similarity_entropy
  min_lag: -1000
  n_folds: 5
  smaller_is_better: false
  weight_decay: 1.0e-05
trial_name: popt_persubject_whisper_embedding
