config_setter_name: popt_per_subject
model_spec:
  constructor_name: linear_probe
  params:
    model_dir: models/popt/pretrained_model
    layer_sizes:
    - 1
    dropout: 0.0
task_config:
  data_params:
    data_root: data
    electrode_file_path: processed_data/all_subject_sig.csv
    target_sr: 2048
    use_high_gamma: false
    use_lip_coords: true
    window_width: 1.0
    per_subject_preprocessing: true
    preprocessing_fn_name:
    - popt_per_subject_feature_extraction
  task_name: iu_boundary_task
  task_specific_config:
    iu_boundaries_csv_path: processed_data/iu_boundaries.csv
    negative_margin_s: 0.5
    negatives_per_positive: 2
training_params:
  batch_size: 32
  early_stopping_metric: f1_logits
  early_stopping_patience: 10
  epochs: 100
  fold_ids:
  - 1
  - 5
  lag_step_size: 500
  learning_rate: 0.001
  loss_weights:
  - 1.0
  losses:
  - bce_with_logits
  max_lag: 1500
  metrics:
  - roc_auc
  - sensitivity_logits
  - specificity_logits
  - f1_logits
  - precision_logits
  - acc_logits
  min_lag: -1000
  n_folds: 5
  smaller_is_better: false
  weight_decay: 1.0e-05
trial_name: popt_persubject_iu_boundary
