model_constructor_name: foundation_model_finetune_attention
config_setter_name: foundation_model_finetune_mlp
model_params: 
  mlp_layer_sizes: [50]
  drop_path: 0.0
  proj_drop: 0.0
  model_dir: /scratch/gpfs/zparis/ECoG-foundation-pretraining/checkpoints/model=patch_dim_2_small-grad_accum=2-encoder_mask_ratio=0.5_29115813/best_checkpoint
training_params:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0
  early_stopping_patience: 20
  n_folds: 5
  min_lag: 0
  max_lag: 400
  lag_step_size: 200
  losses: [nll_embedding, mse]
  loss_weights: [0.99, 0.01]
  metrics: ["cosine_sim"]
  early_stopping_metric: nll_embedding
  smaller_is_better: true
  grad_accumulation_steps: 4
data_params:
  # Cross-model fields
  data_root: data
  embedding_type: gpt-2xl
  embedding_layer: 24
  embedding_pca_dim: 50
  # Window width is set by config setter function to the model's sample length.
  window_width: -1
  preprocessing_fn_name: foundation_model_finetune_mlp
  subject_ids: [9]
  channel_reg_ex: ^G([1-9]|[1-5][0-9]|6[0-4])$
  # Model specific config.
  # preprocessor_params:
  #   global_pool: False
  #   foundation_model_batch_size: 32
  #   model_dir: /scratch/gpfs/zparis/ECoG-foundation-model/checkpoints/grad_accum=2-encoder_mask_ratio=0.5-weight_decay=0.01-proj_drop=0.1-drop_path=0.05-lr=5e-05-precision=no-frame_patch_size=16_29112516/best_checkpoint
trial_name: "{}_finetune_attention_loss={}_loss_weights={}_lr={}_wd={}_bs={}_grad_accum={}"
format_fields: [
    model_params.model_name,
    training_params.losses,
    training_params.loss_weights,
    training_params.learning_rate,
    training_params.weight_decay,
    training_params.batch_size,
    training_params.grad_accumulation_steps,
  ]