model_constructor_name: foundation_model_finetune_mlp
config_setter_name: foundation_model_finetune_mlp
model_params: 
  mlp_layer_sizes: [50]
  model_dir: /scratch/gpfs/zparis/ECoG-foundation-pretraining/checkpoints/model=patch_dim_2_small-grad_accum=2-encoder_mask_ratio=0.5_29115813/best_checkpoint
training_params:
  batch_size: 128
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.001
  early_stopping_patience: 20
  n_folds: 5
  min_lag: -600
  max_lag: 1000
  lag_step_size: 200
  loss_name: nll_embedding
  metrics: ["mse", "cosine_sim"]
  early_stopping_metric: nll_embedding
  smaller_is_better: true
  fold_type: zero_shot_folds
data_params:
  # Cross-model fields
  data_root: data
  embedding_type: gpt-2xl
  embedding_layer: 24
  embedding_pca_dim: 50
  # Window width is set by config setter function to the model's sample length.
  window_width: -1
  preprocessing_fn_name: foundation_model_finetune_mlp
  subject_ids: [9]
  channel_reg_ex: ^G([1-9]|[1-5][0-9]|6[0-4])$
  # Model specific config.
  # preprocessor_params:
trial_name: "{}_finetune_loss={}_lr={}_wd={}_bs={}_grad_accum={}_ft={}"
format_fields: [
    model_params.model_name,
    training_params.loss_name,
    training_params.learning_rate,
    training_params.weight_decay,
    training_params.batch_size,
    training_params.grad_accumulation_steps,
    training_params.fold_type,
  ]