config_setter_name: neural_conv
run_mode: per_subject
task_config:
  task_name: pos_task
  data_params:
    dataset_name: brain_treebank
    dataset_params:
      movie: cars-2
    data_root: data/brain-treebank
    subject_ids: [3, 7, 10]
    use_high_gamma: true
    target_sr: 512
    window_width: 1.0
    preprocessing_fn_name: window_average_neural_data
    preprocessor_params:
      num_average_samples: 8
  task_specific_config:
    labels_path: processed_data/brain_treebank/cars-2/word_labels.csv
training_params:
  tensorboard_logging: false
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  use_lr_scheduler: true
  scheduler_params:
    factor: 0.5
    patience: 10
    min_lr: 0.000001
  early_stopping_patience: 10
  n_folds: 5
  min_lag: -1000
  max_lag: 1100
  lag_step_size: 100
  losses: [cross_entropy]
  metrics: [roc_auc_multiclass, f1, confusion_matrix]
  early_stopping_metric: roc_auc_multiclass
  smaller_is_better: false
  visualize_fold_distribution: false
trial_name: brain_treebank_cars2_pos_per_subject
model_spec:
  constructor_name: ensemble_pitom_model
  params:
    conv_filters: 128
    dropout: 0.2
    num_models: 10
    output_dim: 5
    output_activation: linear
  sub_models: {}
