config_setter_name: foundation_feature_cache
model_spec:
  constructor_name: mlp_probe_decoder
  params:
    layer_sizes:
    - 50
    dropout: 0.0
    use_layer_norm: true
    output_dim: 50
    embedding_dim: 50
  sub_models: {}
task_config:
  data_params:
    data_root: data
    electrode_file_path: null
    target_sr: 2048
    use_high_gamma: false
    window_width: 1.0
    word_column: word
    subject_ids:
    - 7
    channel_reg_ex: null
    per_subject_electrodes: null
    preprocessing_fn_name:
    - disk_cache_preprocessor
    preprocessor_params:
    - base_preprocessing_fn_name:
      - stft_preprocessing
      - foundation_feature_cache
      update_cache_with_missing: true
      base_preprocessor_params:
      - freq_channel_cutoff: 40
        nperseg: 400
        noverlap: 350
        normalizing: zscore
      - mode: normal
        batch_size: 4
        foundation_config_setter_name: brainbert_finetune
        foundation_model_spec:
          constructor_name: brainbert_finetune
          params:
            model_dir: /scratch/gpfs/HASSON/lucy/PODCAST/podcast-benchmark/models/brainbert/pretrained_model
            temporal_patches_to_keep: 3
            feature_cache: true
          feature_cache: true
          per_subject_feature_concat: false
          sub_models: {}
  task_name: whisper_embedding_decoding_task
  task_specific_config:
    embedding_pca_dim: 50
training_params:
  batch_size: 4
  early_stopping_metric: cosine_sim
  early_stopping_patience: 10
  epochs: 100
  lag_step_size: 500
  learning_rate: 1.0e-05
  loss_weights:
  - 1.0
  losses:
  - mse
  max_lag: 1500
  metrics:
  - mse
  - corr
  - cosine_sim
  - cosine_dist
  - nll_embedding
  - pairwise_accuracy
  - similarity_entropy
  min_lag: -1000
  n_folds: 5
  smaller_is_better: false
  weight_decay: 1.0e-05
trial_name: brainbert_subject7_full_whisper_embedding
