config_setter_name: popt_finetune
task_config:
  task_name: word_embedding_decoding_task
  data_params:
    data_root: data
    word_column: word
    electrode_file_path: processed_data/all_subject_sig.csv
    use_high_gamma: false
    target_sr: 2048
    use_lip_coords: true
    window_width: 1.0
  task_specific_config:
    embedding_type: gpt-2xl
    embedding_layer: 24
    embedding_pca_dim: 50
training_params:
  batch_size: 4
  epochs: 100
  learning_rate: 1.0e-05
  weight_decay: 1.0e-05
  early_stopping_patience: 10
  n_folds: 5
  min_lag: -1000
  max_lag: 1500
  lag_step_size: 500
  losses:
  - mse
  loss_weights:
  - 1.0
  metrics:
  - mse
  - corr
  - cosine_sim
  - cosine_dist
  - nll_embedding
  - pairwise_accuracy
  - similarity_entropy
  early_stopping_metric: cosine_sim
  smaller_is_better: false
  fold_ids:
  - 1
  - 5
trial_name: popt_persubject_concat_word_embedding
model_spec:
  constructor_name: popt_finetune
  params:
    model_dir: models/popt/pretrained_model
    brainbert_model_dir: models/brainbert/pretrained_model
    use_lip_coords: true
    use_brainbert: true
    max_coord_value: 5000
    output_dim: 50
    mlp_layer_sizes: []
    dropout: 0.0
    freeze_foundation: true
    num_frozen_layers: 0
  sub_models:
    encoder_model:
      constructor_name: caching_model
      params: {}
      sub_models:
        inner_model:
          constructor_name: popt_encoder
          params: {}
          sub_models: {}
  per_subject_feature_concat: true
