config_setter_name: brainbert_finetune
model_spec:
  constructor_name: brainbert_finetune
  params:
    dropout: 0.0
    freeze_foundation: true
    mlp_layer_sizes: []
    model_dir: models/brainbert/pretrained_model
    output_dim: 1
  sub_models: {}
  feature_cache: true
task_config:
  data_params:
    data_root: data
    electrode_file_path: null
    target_sr: 2048
    use_high_gamma: false
    window_width: 1.0
    subject_ids:
    - 5
    channel_reg_ex: null
    per_subject_electrodes: null
  task_name: volume_level_decoding_task
  task_specific_config:
    allow_resample_audio: true
    audio_path: stimuli/podcast.wav
    audio_sr: 44100
    butter_order: 4
    cutoff_hz: 8.0
    hop_size: 100.0
    target_sr: 512
    window_size: 200.0
    zero_phase: true
training_params:
  batch_size: 4
  early_stopping_metric: corr
  early_stopping_patience: 10
  epochs: 100
  learning_rate: 1.0e-05
  loss_weights:
  - 1.0
  losses:
  - mse
  min_lag: 0
  max_lag: 300
  lag_step_size: 150
  metrics:
  - mse
  - corr
  - r2
  n_folds: 5
  smaller_is_better: false
  weight_decay: 1.0e-05
trial_name: brainbert_subject5_full_volume_level
